package es.upm.dit.isst.gdpr.test;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.HashMap;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
public class AceptarSolicitudTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
	System.setProperty( "webdriver.chrome.driver", "/home/jaime/Universidad/Cuarto/ISST/T6-Pruebas/chromedriver");
	driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void aceptarSolicitudTest() {
    driver.get("http://localhost:8080/GDPR/");
    driver.manage().window().setSize(new Dimension(1691, 993));
    driver.findElement(By.linkText("Log In")).click();
    driver.findElement(By.name("correo")).click();
    //Sustituir por el correo del miembro del CDE
    driver.findElement(By.name("correo")).sendKeys("prueba@prueba");
    driver.findElement(By.cssSelector(".col:nth-child(4)")).click();
    driver.findElement(By.id("passwd")).click();
    //Sustituir por la password del miembro del CDE
    driver.findElement(By.id("passwd")).sendKeys("prueba");
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.cssSelector("tr:nth-child(2) > td:nth-child(1)")).click();
    //Sustituir por el titulo de la solicitud de test
    assertThat(driver.findElement(By.cssSelector("tr:nth-child(2) > td:nth-child(1)")).getText(), is("Esto es una Prueba"));
    driver.findElement(By.cssSelector("tr:nth-child(2) .material-icons")).click();
    driver.findElement(By.cssSelector(".btn-primary:nth-child(3)")).click();
    driver.findElement(By.id("navbarDropdown")).click();
    driver.findElement(By.linkText("Log Out")).click();
    driver.findElement(By.linkText("Log In")).click();
    driver.findElement(By.name("correo")).click();
    //Sustituir por el correo del investigador
    driver.findElement(By.name("correo")).sendKeys("test@test");
    driver.findElement(By.id("passwd")).click();
    //Sustituir por la password del investigador
    driver.findElement(By.id("passwd")).sendKeys("test");
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.cssSelector(".text-success")).click();
    assertThat(driver.findElement(By.cssSelector(".text-success")).getText(), is("Aprobado"));
  }
}
