package es.upm.dit.isst.gdpr.test;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.HashMap;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
public class CrearInvestigadorTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
	System.setProperty( "webdriver.chrome.driver", "/home/jaime/Universidad/Cuarto/ISST/T6-Pruebas/chromedriver");
	driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void crearInvestigadorTest() {
    driver.get("http://localhost:8080/GDPR/");
    driver.manage().window().setSize(new Dimension(1726, 993));
    driver.findElement(By.name("nombre")).click();
    driver.findElement(By.name("nombre")).sendKeys("yo");
    driver.findElement(By.name("apellidos")).click();
    driver.findElement(By.name("apellidos")).sendKeys("mismo");
    driver.findElement(By.name("correo")).click();
    //Sustituir por el correo del investigador que se quiera usar
    driver.findElement(By.name("correo")).sendKeys("test@test");
    driver.findElement(By.name("dni")).click();
    driver.findElement(By.name("dni")).sendKeys("1234");
    driver.findElement(By.cssSelector(".col-md-5")).click();
    driver.findElement(By.id("passwd")).click();
    //Sustituir por la password del investigador que se quiera usar
    driver.findElement(By.id("passwd")).sendKeys("test");
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.cssSelector("th:nth-child(1)")).click();
    assertThat(driver.findElement(By.cssSelector("th:nth-child(1)")).getText(), is("Nombre"));
  }
}
