package es.upm.dit.isst.gdpr.test;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.HashMap;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
public class CrearSolicitudTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
	System.setProperty( "webdriver.chrome.driver", "/home/jaime/Universidad/Cuarto/ISST/T6-Pruebas/chromedriver");
	driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void crearSolicitudTest() {
    driver.get("http://localhost:8080/GDPR/");
    driver.manage().window().setSize(new Dimension(1618, 993));
    driver.findElement(By.linkText("Log In")).click();
    driver.findElement(By.name("correo")).click();
    //Sustituir por el correo del investigador
    driver.findElement(By.name("correo")).sendKeys("test@test");
    driver.findElement(By.id("passwd")).click();
    //Sustituir por la password del investigador 
    driver.findElement(By.id("passwd")).sendKeys("test");
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.cssSelector(".nav-link > .material-icons")).click();
    driver.findElement(By.name("titulo")).click();
    //Sustituir por el titulo de la solicitud que se quiera usar
    driver.findElement(By.name("titulo")).sendKeys("Esto es una Prueba");
    driver.findElement(By.name("fecha")).click();
    driver.findElement(By.name("fecha")).sendKeys("0001-11-11");
    driver.findElement(By.name("fecha")).sendKeys("0011-11-11");
    driver.findElement(By.name("fecha")).sendKeys("0111-11-11");
    driver.findElement(By.name("fecha")).sendKeys("1111-11-11");
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.cssSelector("label > .material-icons")).click();
    //Cambiar por la ruta del archivo que se quira subir
    driver.findElement(By.id("file")).sendKeys("/home/jaime/Universidad/Cuarto/ISST/prueba.pdf");
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.cssSelector("tr:nth-child(2) > td:nth-child(1)")).click();
    //Sustituir por el titulo de la solicitud
    assertThat(driver.findElement(By.cssSelector("tr:nth-child(2) > td:nth-child(1)")).getText(), is("Esto es una Prueba"));
  }
}
