package es.upm.dit.isst.gdpr.test;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.apache.tomcat.util.http.fileupload.UploadContext;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import es.upm.dit.isst.gdpr.dao.UsuarioDAO;
import es.upm.dit.isst.gdpr.dao.UsuarioDAOImplementation;
import es.upm.dit.isst.gdpr.model.Usuario;

import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.HashMap;
import java.util.List;
import java.io.File;
import java.util.ArrayList;
import java.util.Map;
public class CrearSolicitudTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
	System.setProperty( "webdriver.chrome.driver", "chromedriver.exe");
	driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
    UsuarioDAO udao = UsuarioDAOImplementation.getInstance();
    Usuario mcde = new Usuario();
    mcde.setEmail("test@test");
    mcde.setPassword("9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08");
    mcde.setMcde(true);
    udao.create(mcde);
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void crearSolicitudTest() {
    driver.get("http://localhost:8080/GDPR/");
    driver.manage().window().setSize(new Dimension(1920, 1080));
    driver.findElement(By.linkText("Log In")).click();
    driver.findElement(By.name("correo")).click();
    driver.findElement(By.name("correo")).sendKeys("prueba@prueba");
    driver.findElement(By.id("passwd")).click();
    driver.findElement(By.id("passwd")).sendKeys("test");
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.cssSelector(".nav-link > .material-icons")).click();
    driver.findElement(By.name("titulo")).click();
    driver.findElement(By.name("titulo")).sendKeys("Esto es una Prueba");
    driver.findElement(By.name("fecha")).click();
    driver.findElement(By.name("fecha")).click();
    {
      WebElement element = driver.findElement(By.name("fecha"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.name("fecha")).sendKeys("0001-11-11");
    driver.findElement(By.name("fecha")).sendKeys("0011-11-11");
    driver.findElement(By.name("fecha")).sendKeys("0111-11-11");
    driver.findElement(By.name("fecha")).sendKeys("1111-11-11");
    driver.findElement(By.cssSelector(".container:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".btn")).click();
    File file = new File("testData/prueba.pdf");
    driver.findElement(By.id("file")).sendKeys(file.getAbsolutePath());
    
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.cssSelector("td:nth-child(1)")).click();
    assertThat(driver.findElement(By.cssSelector("td:nth-child(1)")).getText(), is("Esto es una Prueba"));
  }
}
